apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yznf1wmx6-go
  janus-idp.io/tekton: yznf1wmx6-go
  backstage.io/kubernetes-id: yznf1wmx6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yznf1wmx6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
