apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yznf1wmx6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yznf1wmx6-go 
  name: yznf1wmx6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yznf1wmx6-go 
